apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: nginx-vivek
    image: nginx:latest
    ports:
      - containerPort: 8080
  - name: watcher
    image: afakharany/watcher
