apiVersion: v1
kind: Service
metadata:
  name: nodeappservice
spec:
  ports:
  - port: 31001
    nodePort: 31002
    targetPort: 3000
    protocol: TCP
  selector:
    app: vivekservice 
  type: NodePort
