apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod5
  name: pod5
spec:
  containers:
  - image: arjunachari12/k8s-demo
    name: pod5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
