apiVersion: v1
kind: Service
metadata:
  name: vivekflaskservice
spec:
  ports:
  - port: 31003
    nodePort: 31004
    targetPort: 5000
    protocol: TCP
  selector:
    app: vivekflask 
  type: NodePort
