apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redisservice
  name: redisservice
spec:
  ports:
  - name: 31110-6379
    port: 31110
    nodePort: 31111
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: NodePort
status:
  loadBalancer: {}
